name: Check Daily Submissions

on:
  push:
    branches:
      - main

jobs:
  check-submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for each member's submission
        id: check_files
        run: |
          day_folder="Day-${{ github.event.issue.number }}"
          members=("user1" "user2" "user3" "user4" "user5")
          all_files_present=true
          
          for member in "${members[@]}"; do
            if ! ls "${day_folder}" | grep -q "$member"; then
              all_files_present=false
              break
            fi
          done

          echo "::set-output name=all_files_present::$all_files_present"

      - name: Close issue if all files are present
        if: steps.check_files.outputs.all_files_present == 'true'
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "All members have uploaded their files. Marking this issue as complete. ✅"
          state: closed
