name: Auto Close Issue After 5 or More Submissions

on:
  push:
    paths:
      - '**/name.py'  # Trigger when a file "name.py" is uploaded in any folder

jobs:
  check_submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count the number of name.py files
        run: |
          # Define the minimum number of submissions required (5 members)
          MIN_SUBMISSIONS=5

          # Count the number of name.py files in the repository
          FILE_COUNT=$(find . -name "name.py" | wc -l)

          # If the number of files is greater than or equal to MIN_SUBMISSIONS
          if [ "$FILE_COUNT" -ge "$MIN_SUBMISSIONS" ]; then
            echo "At least $MIN_SUBMISSIONS members have submitted their work. Closing issue..."
            
            # Close the issue by checking the number of open issues
            ISSUE_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | jq '.[0].number')
            
            # Check if an issue was found and close it
            if [ -n "$ISSUE_NUMBER" ]; then
              curl -X PATCH "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -d '{"state": "closed"}'
            fi
          else
            echo "Not enough members have submitted their work. Current count: $FILE_COUNT"
          fi
