name: Check Daily Submissions

on:
  push:
    branches:
      - main

jobs:
  check-submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Day Number from Issue Title
        id: get_day
        run: |
          # Extract the day number from the issue title (e.g., "Day 1: Task Name" -> 1)
          day_number=$(echo "${{ github.event.issue.title }}" | grep -oP 'Day \K\d+')
          echo "::set-output name=day::$day_number"

      - name: Check for each member's submission
        id: check_files
        run: |
          # Get the day folder from the extracted day number (e.g., Day-1)
          day_folder="Day-${{ steps.get_day.outputs.day }}"
          
          # List of group member GitHub usernames
          members=("user1" "user2" "user3" "user4" "user5")
          
          all_files_present=true
          
          # Check if each member has uploaded a file in the corresponding day folder
          for member in "${members[@]}"; do
            if ! ls "${day_folder}" | grep -q "$member"; then
              all_files_present=false
              break
            fi
          done

          echo "::set-output name=all_files_present::$all_files_present"

      - name: Close issue if all files are present
        if: steps.check_files.outputs.all_files_present == 'true'
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "All members have uploaded their files for this task. Marking it complete. ✅"
          state: closed
