name: Auto Close Issue on File Upload

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    types: [closed]

jobs:
  check-and-close:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check folder contents and close issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // ... (rest of the script remains the same)
