name: Check Daily Submissions

on:
  issues:
    types: [labeled]  # Triggered when a label is added to an issue

jobs:
  check-submissions:
    runs-on: ubuntu-latest

    permissions:
      issues: write  # Permission to update issues

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Use the latest version of checkout action

      - name: Get day label
        id: get_day
        run: |
          # Extract the day number from the issue label
          label=$(echo "${{ github.event.issue.labels }}" | grep -o '"name": "Day-[0-9]*"' | grep -o '[0-9]*')
          echo "::set-output name=day::$label"

      - name: Check for each member's submission
        id: check_files
        run: |
          # Set the day folder and team member usernames
          day_folder="Day-${{ steps.get_day.outputs.day }}"
          members=("joegeorge022" "JoeMartinRince" "Ganesh-Chandran005" "Jobthomas10")
          all_files_present=true
          
          # Check if all team members have uploaded their file in the day folder
          for member in "${members[@]}"; do
            if ! ls "${day_folder}" | grep -q "$member"; then
              all_files_present=false
              break
            fi
          done

          # Output whether all files are present
          echo "::set-output name=all_files_present::$all_files_present"

      - name: Close issue if all files are present
        if: steps.check_files.outputs.all_files_present == 'true'
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "All members have uploaded their files for this task. Marking it complete. ✅"
          state: closed
